name: Build and deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      actions: read
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6
        with:
          fetch-depth: 0 # Fetch all history for what-changed action
      - name: Determine what to do
        id: changed-files
        uses: "nais/what-changed@bc3dad0463b36ad29044134bba5898f0af73c34c" # ratchet:nais/what-changed@main
        with:
          files: .nais/app.yaml,.nais/job.yaml,.nais/valkey.yaml
      - name: Build and push image and SBOM to OCI registry
        if: steps.changed-files.outputs.changed != 'only-inputs'
        uses: nais/docker-build-push@45d352fb62fb52ccb5ff6cba22c047fa02b35321 # ratchet:nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: the-g-team

  deploy-app:
    name: Deploy app and Valkey
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6
      - name: Deploy app and valkey
        uses: nais/deploy/actions/deploy@fa754451577294aae42872a69b888b3470478ec1 # ratchet:nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/app.yaml,.nais/valkey.yaml
          WORKLOAD_IMAGE: ${{ needs.build.outputs.image }}
          WORKLOAD_NAME: god-morgen

  deploy-job:
    name: Deploy job
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6
      - name: Deploy job
        uses: nais/deploy/actions/deploy@fa754451577294aae42872a69b888b3470478ec1 # ratchet:nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .nais/job.yaml
          WORKLOAD_IMAGE: ${{ needs.build.outputs.image }}
          WORKLOAD_NAME: god-morgen
